mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include("polls.urls")),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'
urlpatterns = [
    # To view the index of the website.
    path("", views.IndexView.as_view(), name='index'),
    # To view the question detail i.e. /polls/5
    path("specifies/<int:pk>/", views.DetailView.as_view() , name = 'details'),
    # To view the result.
    # /polls/question_id/result
    path('<int:pk>/result', views.ResultsView.as_view(), name = 'result'),
    # To view the vote.
    # /polls/question_id/vote
    path('<int:question_id>/vote', views.vote, name = 'vote'),
]

mysite/polls/models.py
from django.db import models
import datetime
from django.utils import timezone
# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField("Date published")#Lets see if it is an keyword or just a string argument.
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return timezone.now() - datetime.timedelta(days = 1) <= self.pub_date <= timezone.now()

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)# What does it means.
    choice_text =  models.CharField(max_length = 200)
    votes = models.IntegerField(default = 0)
    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.db.models import F
from .models import Choice, Question
from django.utils import timezone

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
        :5
    ]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/details.html"
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/result.html"

def vote(request, question_id):
    # return HttpResponse('You are voting %s'% pk)
    question = get_object_or_404(Question, pk = question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Phir se question ko display karenge taaki sahi option ko choose karle.
        return render(
            request,
            'polls/details.html',
            {
                "question":question,
                "error_message":"You didn't choose any option",
            }
        )
    else:
        selected_choice.votes = F('votes') + 1 # I don't know if the votes in the database in changed or the selected choice is updated by extracting the value from the votes
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:result', args=(question.id, )))

mysite/polls/templates/polls/details.html
<form action="{%url 'polls:vote' question.id%}" method = "post">
    {%csrf_token%}
    <fieldset>
        {%if error_message%}
            <p>{{error_message}}</p>
        {%endif%}
        <legend><h1>{{question.question_text}}</h1></legend>
        {%for choice in question.choice_set.all%}
            <input type="radio" id="choice{{forloop.counter}}" value={{choice.id}} name = "choice">
            <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
            <!-- Change some of the things and test the results. -->
        {%endfor%}
    </fieldset>
    <input type="submit" value="vote">
</form>

mysite/polls/templates/polls/index.html
{% if latest_question %}
    <ul>
    {% for question in latest_question%}
        <li><a href={%url 'polls:details' question.id%}>{{question.question_text}}</a></li>
    {%endfor%}
    </ul>
{%else%}
    <p>No polls are avail</p>
{%endif%}

mysite/polls/templates/polls/result.html
<h1>{{question.question_text}}</h1>
<ul>
    {%for choice in question.choice_set.all%}
        <li>{{choice.choice_text}}--{{choice.votes}}vote{{choice.votes|pluralize}}</li>
    {%endfor%}
</ul>
<a href={%url 'polls:details' question.id%}>Vote again</a>